apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-service
  labels:
    app: secure-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-service
  template:
    metadata:
      labels:
        app: secure-service
    spec:
      containers:
      - name: secure-service
        image: nginx
        ports:
        - containerPort: 80